spring.application.name=configServer
server.port=8888

# Config Server Git Repository Configuration
spring.cloud.config.server.git.uri=d:/agms/agms/config-repo
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=

# Enable native profile for file system
# spring.profiles.active=native
# spring.cloud.config.server.native.search-locations=d:/agms/agms/config-repo

logging.level.root=INFO
logging.level.org.springframework.cloud.config=DEBUG
logging.level.org.springframework.cloud.config.server.git=DEBUG
